name: Test Suite

on:
  push:
    branches:
      - main
      - 'claude/**'
  pull_request:
    branches:
      - main

jobs:
  unit-and-integration-tests:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test --if-present

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Check for vulnerabilities
        run: |
          echo "Security audit completed"
          npm audit || echo "Found vulnerabilities - review required"

  end-to-end-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          BASE_URL: https://weed365.bill-burkey.workers.dev
          PWA_URL: https://4debcbc8.weed365-pwa.pages.dev
        continue-on-error: false

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [unit-and-integration-tests, security-audit, end-to-end-tests]
    if: always()
    steps:
      - name: Check test results
        run: |
          echo "Unit & Integration Tests: ${{ needs.unit-and-integration-tests.result }}"
          echo "Security Audit: ${{ needs.security-audit.result }}"
          echo "End-to-End Tests: ${{ needs.end-to-end-tests.result }}"

          if [ "${{ needs.unit-and-integration-tests.result }}" != "success" ] || \
             [ "${{ needs.end-to-end-tests.result }}" != "success" ]; then
            echo "Quality gate failed"
            exit 1
          fi

          echo "Quality gate passed"
