-- Detailed list items for featured lists

-- List 1: Horror Movies to Watch While High
INSERT INTO list_items (list_id, title, description, why_high, meta_json, order_position) VALUES
(1, 'Hereditary', 'A family grieves the death of their grandmother, but darker secrets begin to surface. Ari Aster''s debut is a slow-burn nightmare that burrows into your brain.', 'The atmospheric dread builds slowly, perfect for heightened senses. Every frame is meticulously crafted to unsettle you, and when elevated, you''ll catch details that make second viewings even more terrifying.', '{"year": 2018, "director": "Ari Aster", "genre": "Psychological Horror", "where_to_watch": "Amazon Prime, Paramount+"}', 1),
(1, 'The Shining', 'Jack Torrance accepts a caretaker job at the isolated Overlook Hotel, where supernatural forces drive him to madness.', 'Kubrick''s masterpiece becomes a sensory experience when high. The symmetrical shots, the color red, the impossible architecture - everything clicks into place in unsettling ways.', '{"year": 1980, "director": "Stanley Kubrick", "genre": "Psychological Horror", "where_to_watch": "Max, Paramount+"}', 2),
(1, 'The Thing', 'An Antarctic research team discovers a parasitic alien that perfectly imitates any living being. Paranoia ensues as they try to determine who is human.', 'The practical effects are mind-blowing, and the paranoia becomes palpable. Cannabis amplifies the tension and makes you question everything, just like the characters.', '{"year": 1982, "director": "John Carpenter", "genre": "Sci-Fi Horror", "where_to_watch": "Peacock, Amazon Prime"}', 3),
(1, 'Midsommar', 'A couple travels to Sweden for a midsummer festival, but the idyllic commune hides disturbing rituals.', 'Bright, beautiful, and deeply disturbing - Midsommar is horror in daylight. The sensory overload of colors, flowers, and ritualistic horror is intensified when elevated.', '{"year": 2019, "director": "Ari Aster", "genre": "Folk Horror", "where_to_watch": "Amazon Prime, Paramount+"}', 4),
(1, 'Get Out', 'A Black man visits his white girlfriend''s family estate, uncovering a disturbing secret about their seemingly liberal community.', 'The social commentary hits harder, and the hypnosis scenes become genuinely unsettling. Jordan Peele packed every frame with meaning that reveals itself when you''re paying attention.', '{"year": 2017, "director": "Jordan Peele", "genre": "Social Horror", "where_to_watch": "Peacock, Amazon Prime"}', 5),
(1, 'A Quiet Place', 'A family lives in silence, hunted by creatures that attack anything that makes sound.', 'The silence becomes deafening when you''re high. Every tiny sound matters, creating an edge-of-your-seat experience where your own heartbeat becomes part of the tension.', '{"year": 2018, "director": "John Krasinski", "genre": "Creature Horror", "where_to_watch": "Paramount+, Amazon Prime"}', 6),
(1, 'The Witch', 'A 1630s New England family faces supernatural evil lurking in the woods beyond their farm.', 'The period-accurate dialogue and slow-burn atmosphere create an immersive historical nightmare. Cannabis helps you sink into the time period and feel the family''s isolation.', '{"year": 2015, "director": "Robert Eggers", "genre": "Folk Horror", "where_to_watch": "Max, Amazon Prime"}', 7),
(1, 'Sinister', 'A true-crime writer discovers a box of home movies depicting brutal murders, putting his own family in danger.', 'The found-footage elements mixed with cinematic storytelling create genuine scares. The soundtrack by Ulver is haunting, and when high, the demonic imagery becomes unforgettable.', '{"year": 2012, "director": "Scott Derrickson", "genre": "Supernatural Horror", "where_to_watch": "Amazon Prime, Apple TV+"}', 8),
(1, 'It Follows', 'After a sexual encounter, a teenager is pursued by a supernatural entity that only she can see.', 'The dream-logic rules and synth score create an inescapable nightmare. Cannabis amplifies the paranoia - is that person in the background really just a background extra?', '{"year": 2014, "director": "David Robert Mitchell", "genre": "Supernatural Horror", "where_to_watch": "Netflix, Amazon Prime"}', 9),
(1, 'Annihilation', 'A biologist enters a mysterious quarantine zone where the laws of nature don''t apply, searching for her missing husband.', 'Not strictly horror, but the trippy visuals and existential dread make it perfect for an elevated viewing. The Shimmer sequences are breathtaking and terrifying.', '{"year": 2018, "director": "Alex Garland", "genre": "Sci-Fi Horror", "where_to_watch": "Paramount+, Hulu"}', 10),
(1, 'The Descent', 'Six women become trapped in a cave system and hunted by underground creatures.', 'The claustrophobia is real. Even before the creatures appear, the cave sequences create intense anxiety. Cannabis makes you feel like you''re right there with them.', '{"year": 2005, "director": "Neil Marshall", "genre": "Creature Horror", "where_to_watch": "Max, Amazon Prime"}', 11),
(1, 'Evil Dead (2013)', 'Five friends unleash demons in a remote cabin by reading from the Book of the Dead.', 'This remake doesn''t hold back on practical effects and gore. It''s a rollercoaster that keeps intensifying, perfect for those who want their horror extreme and unrelenting.', '{"year": 2013, "director": "Fede Álvarez", "genre": "Supernatural Horror", "where_to_watch": "Max, Amazon Prime"}', 12),
(1, 'The Conjuring', 'Paranormal investigators help a family terrorized by a dark presence in their farmhouse.', 'Classic haunted house done right. The scares are earned, the atmosphere is thick, and cannabis makes every creak and shadow feel more present.', '{"year": 2013, "director": "James Wan", "genre": "Supernatural Horror", "where_to_watch": "Max, Amazon Prime"}', 13);

-- List 2: Mind-Bending Movies
INSERT INTO list_items (list_id, title, description, why_high, meta_json, order_position) VALUES
(2, 'Inception', 'A thief who steals secrets through dream-sharing technology is given a final job: plant an idea in someone''s mind.', 'Dreams within dreams within dreams. When you''re elevated, the layers make more sense and less sense simultaneously. The rotating hallway fight hits different.', '{"year": 2010, "director": "Christopher Nolan", "genre": "Sci-Fi Thriller", "where_to_watch": "Max, Amazon Prime"}', 1),
(2, 'Interstellar', 'Astronauts travel through a wormhole seeking a new home for humanity as Earth becomes uninhabitable.', 'The time dilation scenes and fifth-dimensional tesseract will blow your mind. Cannabis helps you sit with the cosmic scale and emotional weight.', '{"year": 2014, "director": "Christopher Nolan", "genre": "Sci-Fi Drama", "where_to_watch": "Paramount+, Amazon Prime"}', 2),
(2, 'The Matrix', 'A hacker discovers that reality is a simulation and joins a rebellion against the machines.', 'The ultimate stoner movie. "What is real?" hits harder when you''re questioning your own perception. The bullet-time effects are iconic for a reason.', '{"year": 1999, "director": "Wachowski Sisters", "genre": "Sci-Fi Action", "where_to_watch": "Max, Amazon Prime"}', 3),
(2, 'Memento', 'A man with short-term memory loss uses notes and tattoos to hunt for his wife''s killer.', 'The reverse chronology matches the protagonist''s confusion. When elevated, you experience his disorientation firsthand. Multiple viewings reveal new connections.', '{"year": 2000, "director": "Christopher Nolan", "genre": "Psychological Thriller", "where_to_watch": "Amazon Prime, Apple TV+"}', 4),
(2, 'Donnie Darko', 'A troubled teenager is visited by a man in a rabbit suit who tells him the world will end in 28 days.', 'Time travel, parallel universes, and teenage angst. The ambiguity and symbolism give you plenty to think about during and after. Cannabis enhances the dreamlike atmosphere.', '{"year": 2001, "director": "Richard Kelly", "genre": "Sci-Fi Drama", "where_to_watch": "Amazon Prime, Apple TV+"}', 5),
(2, 'Arrival', 'A linguist is recruited to communicate with alien visitors and learn their true purpose on Earth.', 'The non-linear time concept becomes intuitive when you''re in the right mindset. The emotional payoff hits like a truck when you understand how time works for the aliens.', '{"year": 2016, "director": "Denis Villeneuve", "genre": "Sci-Fi Drama", "where_to_watch": "Paramount+, Amazon Prime"}', 6),
(2, 'Eternal Sunshine of the Spotless Mind', 'A couple undergoes a procedure to erase each other from their memories after their relationship ends.', 'Love, loss, and memory collide in this surreal journey. Cannabis makes the emotional beats land harder and the memory manipulation sequences more immersive.', '{"year": 2004, "director": "Michel Gondry", "genre": "Romantic Sci-Fi", "where_to_watch": "Peacock, Amazon Prime"}', 7),
(2, 'Primer', 'Two engineers accidentally discover time travel in their garage and struggle with the consequences.', 'The most scientifically accurate time travel movie is also the most confusing. You''ll need a diagram afterward, but the puzzle is part of the fun when elevated.', '{"year": 2004, "director": "Shane Carruth", "genre": "Sci-Fi Thriller", "where_to_watch": "Amazon Prime, Apple TV+"}', 8),
(2, 'Shutter Island', 'A U.S. Marshal investigates a missing patient at a hospital for the criminally insane on a remote island.', 'The twist is legendary, but the journey there is a paranoid fever dream. Cannabis amplifies the unreliable narrator experience and Gothic atmosphere.', '{"year": 2010, "director": "Martin Scorsese", "genre": "Psychological Thriller", "where_to_watch": "Paramount+, Amazon Prime"}', 9),
(2, 'Predestination', 'A temporal agent embarks on his final mission to stop an elusive terrorist known as the "Fizzle Bomber."', 'Time travel paradoxes that will twist your brain into knots. The less you know going in, the better. Cannabis helps you accept the impossible logic.', '{"year": 2014, "director": "The Spierig Brothers", "genre": "Sci-Fi Thriller", "where_to_watch": "Netflix, Amazon Prime"}', 10);

-- List 3: Comedy Movies That Hit Different Stoned
INSERT INTO list_items (list_id, title, description, why_high, meta_json, order_position) VALUES
(3, 'Pineapple Express', 'A process server and his dealer go on the run after witnessing a murder.', 'It''s literally about weed. The action-comedy hybrid works perfectly when you''re in the right state of mind. "Dopest dope I''ve ever smoked."', '{"year": 2008, "director": "David Gordon Green", "genre": "Action Comedy", "where_to_watch": "Netflix, Amazon Prime"}', 1),
(3, 'Superbad', 'Two high school friends attempt to buy alcohol for a party before they graduate.', 'The absurd escalation and Seth/Evan dynamic become even funnier. The McLovin scenes are legendary, and when you''re high, you''ll quote them for days.', '{"year": 2007, "director": "Greg Mottola", "genre": "Teen Comedy", "where_to_watch": "Netflix, Amazon Prime"}', 2),
(3, 'The Big Lebowski', 'The Dude, a slacker, is mistaken for a millionaire and gets caught up in a bizarre kidnapping plot.', 'The ultimate stoner cult classic. Every rewatch reveals new details. The dream sequences and meandering plot match a cannabis-enhanced viewing perfectly.', '{"year": 1998, "director": "Coen Brothers", "genre": "Crime Comedy", "where_to_watch": "Peacock, Amazon Prime"}', 3),
(3, 'Step Brothers', 'Two middle-aged men become stepbrothers and immediately hate each other.', 'The absurdist humor and improvised lines hit differently when elevated. The bunk bed scene is a masterpiece of physical comedy.', '{"year": 2008, "director": "Adam McKay", "genre": "Comedy", "where_to_watch": "Netflix, Amazon Prime"}', 4),
(3, 'Scott Pilgrim vs. the World', 'A slacker must defeat his new girlfriend''s seven evil exes to date her.', 'Video game logic, comic book visuals, and rapid-fire humor. Cannabis helps you appreciate the visual creativity and Edgar Wright''s editing style.', '{"year": 2010, "director": "Edgar Wright", "genre": "Action Comedy", "where_to_watch": "Netflix, Amazon Prime"}', 5),
(3, 'Hot Fuzz', 'A skilled London cop is transferred to a quiet village where a series of mysterious deaths occur.', 'Edgar Wright''s action-comedy is packed with visual gags and callbacks. When you''re high, you''ll catch jokes you missed the first three times.', '{"year": 2007, "director": "Edgar Wright", "genre": "Action Comedy", "where_to_watch": "Peacock, Amazon Prime"}', 6),
(3, 'Anchorman', 'A legendary news anchor struggles with the arrival of an ambitious female reporter in the 1970s.', 'Will Ferrell at his peak absurdity. The non-sequiturs and escalations are funnier when your brain is more receptive to the ridiculous.', '{"year": 2004, "director": "Adam McKay", "genre": "Comedy", "where_to_watch": "Paramount+, Amazon Prime"}', 7),
(3, 'Dazed and Confused', 'High school and middle school students deal with the last day of school in 1976.', 'It''s about getting high, but it''s also about nostalgia and youth. The vibe is perfect for a chill evening session. Alright alright alright.', '{"year": 1993, "director": "Richard Linklater", "genre": "Coming-of-Age Comedy", "where_to_watch": "Paramount+, Amazon Prime"}', 8),
(3, 'Tropic Thunder', 'Actors filming a war movie are dropped into real danger when a plan to scare them goes wrong.', 'The meta-comedy and absurd action are elevated when you''re elevated. Robert Downey Jr.''s performance is unhinged in the best way.', '{"year": 2008, "director": "Ben Stiller", "genre": "Action Comedy", "where_to_watch": "Paramount+, Amazon Prime"}', 9),
(3, 'Shaun of the Dead', 'A man tries to get his life together while a zombie apocalypse unfolds around him.', 'Horror-comedy perfection. The visual gags and callbacks are numerous, and cannabis helps you appreciate the clever writing and choreography.', '{"year": 2004, "director": "Edgar Wright", "genre": "Horror Comedy", "where_to_watch": "Peacock, Amazon Prime"}', 10),
(3, 'Zombieland', 'A cowardly survivor navigates a zombie-infested America with an unlikely group of survivors.', 'The rules, the celebrity cameo, the slow-motion zombie kills - everything works better when you''re in the zone. The humor is dark but accessible.', '{"year": 2009, "director": "Ruben Fleischer", "genre": "Horror Comedy", "where_to_watch": "Netflix, Amazon Prime"}', 11),
(3, 'Rush Hour', 'A Hong Kong detective and an LAPD detective must work together to rescue the Chinese Consul''s kidnapped daughter.', 'Jackie Chan and Chris Tucker''s chemistry is electric. The action-comedy balance is perfect, and the blooper reel at the end is mandatory viewing.', '{"year": 1998, "director": "Brett Ratner", "genre": "Action Comedy", "where_to_watch": "Netflix, Amazon Prime"}', 12),
(3, 'Bridesmaids', 'A woman competes with her best friend''s other bridesmaids to be the maid of honor.', 'Hilarious and heartfelt. The airplane scene and food poisoning scene are legendarily funny, especially with lowered inhibitions.', '{"year": 2011, "director": "Paul Feig", "genre": "Comedy", "where_to_watch": "Peacock, Amazon Prime"}', 13),
(3, 'The Grand Budapest Hotel', 'A concierge and his protégé become embroiled in a theft and murder at a famous European hotel.', 'Wes Anderson''s symmetrical visuals and pastel colors are a feast for elevated eyes. The whimsical storytelling and deadpan humor land perfectly.', '{"year": 2014, "director": "Wes Anderson", "genre": "Comedy Drama", "where_to_watch": "Peacock, Amazon Prime"}', 14),
(3, '21 Jump Street', 'Two cops go undercover as high school students to bust a drug ring.', 'The self-aware humor and Jonah Hill/Channing Tatum chemistry create non-stop laughs. The drug scenes are ironically perfect for this list.', '{"year": 2012, "director": "Phil Lord, Christopher Miller", "genre": "Action Comedy", "where_to_watch": "Hulu, Amazon Prime"}', 15);

-- List 5: Albums Perfect for a Smoke Session
INSERT INTO list_items (list_id, title, description, why_high, meta_json, order_position) VALUES
(5, 'Dark Side of the Moon - Pink Floyd', 'The iconic concept album about life, death, time, and mental illness. A sonic journey from start to finish.', 'The production quality is unmatched. Every sound pans, echoes, and builds in ways that cannabis helps you fully appreciate. Headphones mandatory.', '{"year": 1973, "genre": "Progressive Rock", "runtime": "42:49", "standout_tracks": ["Time", "Money", "Us and Them"]}', 1),
(5, 'Currents - Tame Impala', 'Kevin Parker''s psychedelic pop masterpiece about transformation and letting go.', 'The swirling synths and layered vocals create a sonic bath. Each track flows seamlessly, and elevated listening reveals the intricate production details.', '{"year": 2015, "genre": "Psychedelic Pop", "runtime": "51:18", "standout_tracks": ["Let It Happen", "The Less I Know The Better", "New Person, Same Old Mistakes"]}', 2),
(5, 'To Pimp a Butterfly - Kendrick Lamar', 'A jazz-infused hip-hop odyssey exploring Black identity, fame, and survival in America.', 'The musicality is incredible - jazz, funk, soul all woven together. Cannabis helps you catch the double meanings and appreciate the ambitious scope.', '{"year": 2015, "genre": "Hip-Hop/Jazz", "runtime": "78:50", "standout_tracks": ["King Kunta", "The Blacker The Berry", "Alright"]}', 3),
(5, 'In Rainbows - Radiohead', 'Radiohead''s most accessible yet complex album, exploring love and human connection.', 'The warm analog production and experimental song structures reward elevated listening. "Weird Fishes" will transport you to another dimension.', '{"year": 2007, "genre": "Alternative/Experimental", "runtime": "42:39", "standout_tracks": ["Weird Fishes/Arpeggi", "Nude", "Reckoner"]}', 4),
(5, 'Blonde - Frank Ocean', 'An intimate, experimental R&B album about love, loss, and identity.', 'The minimalist production leaves space for Frank''s voice to shine. Cannabis enhances the emotional vulnerability and helps you sink into the atmosphere.', '{"year": 2016, "genre": "R&B/Alternative", "runtime": "60:07", "standout_tracks": ["Nikes", "Ivy", "Self Control"]}', 5),
(5, 'Lonerism - Tame Impala', 'Kevin Parker''s exploration of isolation wrapped in lush psychedelic production.', 'The hazy, reverb-drenched soundscapes perfectly match an elevated state. Each listen reveals new layers hiding in the mix.', '{"year": 2012, "genre": "Psychedelic Rock", "runtime": "51:53", "standout_tracks": ["Feels Like We Only Go Backwards", "Elephant", "Mind Mischief"]}', 6),
(5, 'Wish You Were Here - Pink Floyd', 'A tribute to lost bandmate Syd Barrett, exploring absence and the music industry.', 'Slightly more accessible than Dark Side, but equally immersive. The extended instrumentals are perfect for letting your mind wander.', '{"year": 1975, "genre": "Progressive Rock", "runtime": "44:28", "standout_tracks": ["Shine On You Crazy Diamond", "Wish You Were Here"]}', 7),
(5, 'Channel Orange - Frank Ocean', 'Frank''s major label debut exploring youth, love, and Los Angeles.', 'The storytelling is cinematic. Cannabis helps you visualize the characters and scenarios Frank describes in vivid detail.', '{"year": 2012, "genre": "R&B/Soul", "runtime": "62:18", "standout_tracks": ["Thinkin Bout You", "Pyramids", "Super Rich Kids"]}', 8),
(5, 'The Chronic - Dr. Dre', 'The album that defined G-funk and solidified West Coast hip-hop dominance.', 'It''s literally about smoking weed. The laid-back grooves and synth bass lines are the definition of vibes. A cultural touchstone.', '{"year": 1992, "genre": "Hip-Hop/G-Funk", "runtime": "62:34", "standout_tracks": ["Nuthin'' but a ''G'' Thang", "Let Me Ride", "The Day the Niggaz Took Over"]}', 9),
(5, 'Merriweather Post Pavilion - Animal Collective', 'Experimental pop at its most accessible, combining samples and harmonies in unexpected ways.', 'The textural layers and unconventional structures make more sense when you''re open to them. A rewarding challenge for elevated ears.', '{"year": 2009, "genre": "Experimental Pop", "runtime": "55:05", "standout_tracks": ["My Girls", "Summertime Clothes", "Brother Sport"]}', 10),
(5, 'Midnight Marauders - A Tribe Called Quest', 'The pinnacle of jazz rap, smooth and intelligent with impeccable production.', 'The bass lines are infectious, the samples are chef''s kiss, and Q-Tip''s flow is hypnotic. Perfect for nodding your head and zoning out.', '{"year": 1993, "genre": "Hip-Hop/Jazz Rap", "runtime": "51:14", "standout_tracks": ["Electric Relaxation", "Award Tour", "8 Million Stories"]}', 11),
(5, 'Discovery - Daft Punk', 'French house robots create an album that''s equally suited for dancing and spacing out.', 'The robotic vocoder vocals and disco samples create euphoria. "Digital Love" hits different when elevated - pure joy in audio form.', '{"year": 2001, "genre": "Electronic/House", "runtime": "60:50", "standout_tracks": ["One More Time", "Digital Love", "Face to Face"]}', 12);

-- List 9: Easy Munchie Recipes
INSERT INTO list_items (list_id, title, description, why_high, meta_json, order_position) VALUES
(9, 'Grilled Cheese 2.0', 'The classic elevated with caramelized onions, multiple cheeses, and a touch of garlic butter.', 'It''s simple enough to make while elevated but fancy enough to feel like a real meal. The cheese pull is deeply satisfying.', '{"difficulty": "Easy", "time": "15 min", "serves": "1-2", "key_ingredients": ["bread", "cheddar", "mozzarella", "butter", "garlic"]}', 1),
(9, 'Nachos Supreme', 'Tortilla chips piled high with cheese, beans, jalapeños, sour cream, and whatever else you''ve got.', 'Endlessly customizable and impossible to mess up. Layer, microwave, enjoy. The combinations are endless.', '{"difficulty": "Easy", "time": "10 min", "serves": "2-4", "key_ingredients": ["tortilla chips", "cheese", "beans", "salsa", "sour cream"]}', 2),
(9, 'Peanut Butter Banana Toast', 'Toasted bread with peanut butter, sliced banana, honey, and a sprinkle of cinnamon.', 'Sweet, filling, and requires zero cooking skills. The Elvis knew what was up. Add chocolate chips if you''re feeling fancy.', '{"difficulty": "Very Easy", "time": "5 min", "serves": "1", "key_ingredients": ["bread", "peanut butter", "banana", "honey"]}', 3),
(9, 'Quesadilla Deluxe', 'Cheese and whatever protein/veg you have folded in a tortilla and crisped in a pan.', 'One pan, minimal effort, maximum satisfaction. The crispy tortilla and melted cheese combo is unbeatable. Dip in sour cream and salsa.', '{"difficulty": "Easy", "time": "10 min", "serves": "1-2", "key_ingredients": ["tortillas", "cheese", "chicken/beans", "peppers"]}', 4),
(9, 'Ramen Upgrade', 'Instant ramen enhanced with a soft-boiled egg, green onions, sesame oil, and sriracha.', 'Takes poverty ramen to restaurant-quality with five minutes of effort. The egg yolk mixing into the broth is magic.', '{"difficulty": "Easy", "time": "8 min", "serves": "1", "key_ingredients": ["instant ramen", "egg", "green onions", "sesame oil", "sriracha"]}', 5),
(9, 'Pizza Bagels', 'Bagels topped with marinara, mozzarella, and pepperoni, then broiled until bubbly.', 'Kid-food perfection. Customize each half differently. The toasted bagel provides the perfect crunchy base.', '{"difficulty": "Very Easy", "time": "10 min", "serves": "1-2", "key_ingredients": ["bagels", "marinara", "mozzarella", "pepperoni"]}', 6),
(9, 'Avocado Toast Actually Good', 'Toasted sourdough with mashed avocado, everything bagel seasoning, lemon, and a fried egg.', 'Yes, it''s trendy, but it''s trendy for a reason. The creaminess plus runny yolk is perfection. Instagram optional.', '{"difficulty": "Easy", "time": "10 min", "serves": "1", "key_ingredients": ["sourdough", "avocado", "egg", "everything seasoning", "lemon"]}', 7),
(9, 'Taco Bowls', 'Skip the tortilla, layer rice, beans, meat, cheese, and toppings in a bowl.', 'All the taco flavor, none of the structural failure. Easy to assemble while elevated, and you can eat it with a spoon.', '{"difficulty": "Easy", "time": "15 min", "serves": "2", "key_ingredients": ["rice", "beans", "ground beef", "cheese", "salsa", "sour cream"]}', 8),
(9, 'Loaded Fries', 'Frozen fries topped with melted cheese, bacon bits, sour cream, and green onions.', 'Poutine-adjacent perfection. Bake the fries, pile on toppings, return to oven. Canadian comfort food made easy.', '{"difficulty": "Easy", "time": "25 min", "serves": "2-3", "key_ingredients": ["frozen fries", "cheese", "bacon", "sour cream", "green onions"]}', 9),
(9, 'Breakfast Burrito', 'Scrambled eggs, cheese, bacon/sausage, hash browns, salsa wrapped in a large tortilla.', 'Breakfast any time. Wrap it tight in foil and it''s portable. The carbs will hit just right when hunger strikes.', '{"difficulty": "Easy", "time": "15 min", "serves": "1-2", "key_ingredients": ["tortillas", "eggs", "cheese", "breakfast meat", "hash browns"]}', 10),
(9, 'Mac and Cheese Cups', 'Boxed mac and cheese portioned into muffin tins with breadcrumb topping, baked until crispy.', 'Individual serving sizes with a crispy top. Kids'' food elevated (literally and figuratively). Make a batch ahead of time.', '{"difficulty": "Easy", "time": "20 min", "serves": "6", "key_ingredients": ["box mac and cheese", "breadcrumbs", "butter"]}', 11),
(9, 'Caprese Skewers', 'Cherry tomatoes, fresh mozzarella, and basil on toothpicks, drizzled with balsamic.', 'Feels fancy, requires zero cooking. The fresh flavors are surprisingly satisfying. Classy munchies for refined stoners.', '{"difficulty": "Very Easy", "time": "5 min", "serves": "2-4", "key_ingredients": ["cherry tomatoes", "fresh mozzarella", "basil", "balsamic glaze"]}', 12),
(9, 'S''mores in the Microwave', 'Graham crackers, chocolate, and marshmallows microwaved for 15 seconds.', 'Campfire nostalgia without leaving your couch. The marshmallow puffs up perfectly. Watch it closely or it''ll explode.', '{"difficulty": "Very Easy", "time": "2 min", "serves": "1", "key_ingredients": ["graham crackers", "chocolate", "marshmallows"]}', 13),
(9, 'Smoothie Bowl', 'Frozen fruit blended thick, topped with granola, fresh fruit, and honey.', 'Healthy munchies that taste like dessert. The thick texture is satisfying, and you can customize endlessly. Your body will thank you.', '{"difficulty": "Easy", "time": "10 min", "serves": "1", "key_ingredients": ["frozen fruit", "milk/juice", "granola", "honey"]}', 14),
(9, 'Fried Rice Fast', 'Day-old rice stir-fried with egg, frozen veggies, soy sauce, and sesame oil.', 'Uses leftovers, comes together in one pan, tastes better than takeout. The key is day-old rice - fresh rice gets mushy.', '{"difficulty": "Medium", "time": "15 min", "serves": "2", "key_ingredients": ["cooked rice", "egg", "frozen veggies", "soy sauce", "sesame oil"]}', 15),
(9, 'Chocolate Mug Cake', 'Cake batter mixed in a mug, microwaved for 90 seconds. Instant warm chocolate cake.', 'Dangerous knowledge to have when elevated. Warm chocolate cake in under 2 minutes. Add ice cream for extra points.', '{"difficulty": "Easy", "time": "5 min", "serves": "1", "key_ingredients": ["flour", "sugar", "cocoa powder", "egg", "milk", "oil"]}', 16),
(9, 'Buffalo Chicken Dip', 'Shredded chicken, cream cheese, buffalo sauce, and cheese baked until bubbly. Serve with chips.', 'Party dip perfection. Can be made in advance, reheated when needed. Spicy, creamy, addictive. Keep napkins nearby.', '{"difficulty": "Easy", "time": "25 min", "serves": "4-6", "key_ingredients": ["chicken", "cream cheese", "buffalo sauce", "cheddar", "chips"]}', 17),
(9, 'Breakfast Sandwich', 'Egg, cheese, and breakfast meat between an English muffin or bagel.', 'McDonald''s quality at home. The key is timing everything to finish simultaneously. Portable and satisfying.', '{"difficulty": "Easy", "time": "10 min", "serves": "1", "key_ingredients": ["English muffin", "egg", "cheese", "bacon/sausage"]}', 18);
